version: "3.8"

services:
    backend:
      image: loesterbotelho/backend:v1
      container_name: backend
      restart: always
      build:
        context: .
        dockerfile: backend.dockerfile
      environment:
        - SPRING_PROFILES_ACTIVE=prod   
        - SPRING_DATASOURCE_URL=jdbc:postgresql://172.17.0.1:5432/postgres
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=PA@password  
        
      ports:
        - "8080:8080"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://34.252.79.7:8080/health"]
        interval: 30s
        timeout: 10s
        retries: 5
      volumes:
        - backend_data:/app/data


volumes:
  backend_data:
    driver: local

networks:
  loester-network:
    driver: bridge
    
